/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDebugInterpreterV1,
  IDebugInterpreterV1Interface,
} from "../../../../../lib/rain.interface.interpreter/src/unstable/IDebugInterpreterV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IInterpreterStoreV1",
        name: "store",
        type: "address",
      },
      {
        internalType: "FullyQualifiedNamespace",
        name: "namespace",
        type: "uint256",
      },
      {
        internalType: "bytes[]",
        name: "compiledSources",
        type: "bytes[]",
      },
      {
        internalType: "uint256[]",
        name: "constants",
        type: "uint256[]",
      },
      {
        internalType: "uint256[][]",
        name: "context",
        type: "uint256[][]",
      },
      {
        internalType: "uint256[]",
        name: "initialStack",
        type: "uint256[]",
      },
      {
        internalType: "SourceIndex",
        name: "sourceIndex_",
        type: "uint16",
      },
    ],
    name: "offchainDebugEval",
    outputs: [
      {
        internalType: "uint256[]",
        name: "finalStack",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "kvs",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDebugInterpreterV1__factory {
  static readonly abi = _abi;
  static createInterface(): IDebugInterpreterV1Interface {
    return new utils.Interface(_abi) as IDebugInterpreterV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDebugInterpreterV1 {
    return new Contract(address, _abi, signerOrProvider) as IDebugInterpreterV1;
  }
}
