/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as libEvidence from "./LibEvidence";
export type { libEvidence };
import type * as verifyCallback from "./VerifyCallback";
export type { verifyCallback };
