/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface PhasedTestInterface extends utils.Interface {
  functions: {
    "condition()": FunctionFragment;
    "currentPhase()": FunctionFragment;
    "phaseAtTime(uint32[8],uint256)": FunctionFragment;
    "phaseTimes(uint256)": FunctionFragment;
    "runsOnlyAtLeastPhase(uint256)": FunctionFragment;
    "runsOnlyPhase(uint256)": FunctionFragment;
    "testScheduleNextPhase(uint256)": FunctionFragment;
    "timeForPhase(uint32[8],uint256)": FunctionFragment;
    "toggleCondition()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "condition"
      | "currentPhase"
      | "phaseAtTime"
      | "phaseTimes"
      | "runsOnlyAtLeastPhase"
      | "runsOnlyPhase"
      | "testScheduleNextPhase"
      | "timeForPhase"
      | "toggleCondition"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "condition", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "phaseAtTime",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "phaseTimes",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "runsOnlyAtLeastPhase",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "runsOnlyPhase",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "testScheduleNextPhase",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "timeForPhase",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleCondition",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "condition", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "phaseAtTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "phaseTimes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "runsOnlyAtLeastPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runsOnlyPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testScheduleNextPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeForPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleCondition",
    data: BytesLike
  ): Result;

  events: {
    "PhaseScheduled(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PhaseScheduled"): EventFragment;
}

export interface PhaseScheduledEventObject {
  sender: string;
  newPhase: BigNumber;
  scheduledTime: BigNumber;
}
export type PhaseScheduledEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  PhaseScheduledEventObject
>;

export type PhaseScheduledEventFilter = TypedEventFilter<PhaseScheduledEvent>;

export interface PhasedTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PhasedTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    condition(overrides?: CallOverrides): Promise<[boolean]>;

    currentPhase(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { phase_: BigNumber }>;

    phaseAtTime(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { phase_: BigNumber }>;

    phaseTimes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    runsOnlyAtLeastPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    runsOnlyPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    testScheduleNextPhase(
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    timeForPhase(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { timestamp_: BigNumber }>;

    toggleCondition(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  condition(overrides?: CallOverrides): Promise<boolean>;

  currentPhase(overrides?: CallOverrides): Promise<BigNumber>;

  phaseAtTime(
    phaseTimes_: PromiseOrValue<BigNumberish>[],
    timestamp_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  phaseTimes(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  runsOnlyAtLeastPhase(
    phase_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  runsOnlyPhase(
    phase_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  testScheduleNextPhase(
    timestamp_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  timeForPhase(
    phaseTimes_: PromiseOrValue<BigNumberish>[],
    phase_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  toggleCondition(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    condition(overrides?: CallOverrides): Promise<boolean>;

    currentPhase(overrides?: CallOverrides): Promise<BigNumber>;

    phaseAtTime(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    phaseTimes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    runsOnlyAtLeastPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    runsOnlyPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    testScheduleNextPhase(
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    timeForPhase(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    toggleCondition(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "PhaseScheduled(address,uint256,uint256)"(
      sender?: null,
      newPhase?: null,
      scheduledTime?: null
    ): PhaseScheduledEventFilter;
    PhaseScheduled(
      sender?: null,
      newPhase?: null,
      scheduledTime?: null
    ): PhaseScheduledEventFilter;
  };

  estimateGas: {
    condition(overrides?: CallOverrides): Promise<BigNumber>;

    currentPhase(overrides?: CallOverrides): Promise<BigNumber>;

    phaseAtTime(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    phaseTimes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    runsOnlyAtLeastPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    runsOnlyPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testScheduleNextPhase(
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    timeForPhase(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    toggleCondition(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    condition(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentPhase(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    phaseAtTime(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    phaseTimes(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    runsOnlyAtLeastPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    runsOnlyPhase(
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testScheduleNextPhase(
      timestamp_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    timeForPhase(
      phaseTimes_: PromiseOrValue<BigNumberish>[],
      phase_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toggleCondition(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
