/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../common";

export interface LibIntegrityCheckTestInterface extends utils.Interface {
  functions: {
    "applyFn0(uint256)": FunctionFragment;
    "applyFn1(uint256)": FunctionFragment;
    "applyFn2(uint256)": FunctionFragment;
    "applyFn3(uint256)": FunctionFragment;
    "applyFn4(uint256)": FunctionFragment;
    "applyFn5(uint256,uint256)": FunctionFragment;
    "applyFn6(uint256,uint256)": FunctionFragment;
    "applyFn7(uint256,uint256)": FunctionFragment;
    "applyFn8(uint256,uint256)": FunctionFragment;
    "applyFnN(uint256,uint256)": FunctionFragment;
    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)": FunctionFragment;
    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)": FunctionFragment;
    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)": FunctionFragment;
    "popUnderflowCheck(bytes[],uint256[],uint256,uint256,uint256,uint256)": FunctionFragment;
    "push(bytes[],uint256[],uint256,uint256,uint256)": FunctionFragment;
    "push(bytes[],uint256[],uint256,uint256)": FunctionFragment;
    "pushIgnoreHighwater(bytes[],uint256[],uint256,uint256)": FunctionFragment;
    "syncStackMaxTop(bytes[],uint256[],uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "applyFn0"
      | "applyFn1"
      | "applyFn2"
      | "applyFn3"
      | "applyFn4"
      | "applyFn5"
      | "applyFn6"
      | "applyFn7"
      | "applyFn8"
      | "applyFnN"
      | "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)"
      | "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)"
      | "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)"
      | "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)"
      | "popUnderflowCheck"
      | "push(bytes[],uint256[],uint256,uint256,uint256)"
      | "push(bytes[],uint256[],uint256,uint256)"
      | "pushIgnoreHighwater"
      | "syncStackMaxTop"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "applyFn0",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn1",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn2",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn3",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn4",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn5",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn6",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn7",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFn8",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "applyFnN",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "popUnderflowCheck",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "push(bytes[],uint256[],uint256,uint256,uint256)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "push(bytes[],uint256[],uint256,uint256)",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pushIgnoreHighwater",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "syncStackMaxTop",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "applyFn0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn4", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn5", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn6", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn7", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFn8", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "applyFnN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "popUnderflowCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "push(bytes[],uint256[],uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "push(bytes[],uint256[],uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pushIgnoreHighwater",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncStackMaxTop",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LibIntegrityCheckTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibIntegrityCheckTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    applyFn0(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn1(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn2(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn3(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn4(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn5(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn6(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn7(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFn8(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    applyFnN(
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      stackBottom_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { stackTopAfter_: BigNumber }>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { stackTopAfter_: BigNumber }>;

    popUnderflowCheck(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "push(bytes[],uint256[],uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        newStackMaxTop: BigNumber;
      }
    >;

    "push(bytes[],uint256[],uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        newStackMaxTop: BigNumber;
      }
    >;

    pushIgnoreHighwater(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        newStackMaxTop: BigNumber;
      }
    >;

    syncStackMaxTop(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  applyFn0(
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn1(
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn2(
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn3(
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn4(
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn5(
    stackTop_: PromiseOrValue<BigNumberish>,
    length_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn6(
    stackTop_: PromiseOrValue<BigNumberish>,
    length_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn7(
    stackTop_: PromiseOrValue<BigNumberish>,
    length_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFn8(
    stackTop_: PromiseOrValue<BigNumberish>,
    length_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  applyFnN(
    stackTop_: PromiseOrValue<BigNumberish>,
    n_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)"(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    sourceIndex_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    minStackOutputs_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)"(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    sourceIndex_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    minStackOutputs_: PromiseOrValue<BigNumberish>,
    stackBottom_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)"(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    stackBottom_: PromiseOrValue<BigNumberish>,
    stackHighwater_: PromiseOrValue<BigNumberish>,
    stackMaxTop_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    n_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)"(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    stackBottom_: PromiseOrValue<BigNumberish>,
    stackHighwater_: PromiseOrValue<BigNumberish>,
    stackMaxTop_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  popUnderflowCheck(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    stackBottom_: PromiseOrValue<BigNumberish>,
    stackHighwater_: PromiseOrValue<BigNumberish>,
    stackMaxTop_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  "push(bytes[],uint256[],uint256,uint256,uint256)"(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    stackMaxTop_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    n_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      stackTopAfter_: BigNumber;
      newStackMaxTop: BigNumber;
    }
  >;

  "push(bytes[],uint256[],uint256,uint256)"(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    stackMaxTop_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      stackTopAfter_: BigNumber;
      newStackMaxTop: BigNumber;
    }
  >;

  pushIgnoreHighwater(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    stackMaxTop_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      stackTopAfter_: BigNumber;
      newStackMaxTop: BigNumber;
    }
  >;

  syncStackMaxTop(
    sources_: PromiseOrValue<BytesLike>[],
    constants_: PromiseOrValue<BigNumberish>[],
    stackMaxTop_: PromiseOrValue<BigNumberish>,
    stackTop_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    applyFn0(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn1(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn2(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn3(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn4(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn5(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn6(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn7(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn8(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFnN(
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      stackBottom_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    popUnderflowCheck(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "push(bytes[],uint256[],uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        newStackMaxTop: BigNumber;
      }
    >;

    "push(bytes[],uint256[],uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        newStackMaxTop: BigNumber;
      }
    >;

    pushIgnoreHighwater(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        newStackMaxTop: BigNumber;
      }
    >;

    syncStackMaxTop(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    applyFn0(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn1(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn2(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn3(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn4(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn5(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn6(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn7(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFn8(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    applyFnN(
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      stackBottom_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    popUnderflowCheck(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "push(bytes[],uint256[],uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "push(bytes[],uint256[],uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pushIgnoreHighwater(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    syncStackMaxTop(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    applyFn0(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn1(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn2(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn3(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn4(
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn5(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn6(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn7(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFn8(
      stackTop_: PromiseOrValue<BigNumberish>,
      length_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    applyFnN(
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "ensureIntegrityTest(bytes[],uint256[],uint16,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      sourceIndex_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>,
      stackBottom_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pop(bytes[],uint256[],uint256,uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    popUnderflowCheck(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackBottom_: PromiseOrValue<BigNumberish>,
      stackHighwater_: PromiseOrValue<BigNumberish>,
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "push(bytes[],uint256[],uint256,uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      n_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "push(bytes[],uint256[],uint256,uint256)"(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pushIgnoreHighwater(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    syncStackMaxTop(
      sources_: PromiseOrValue<BytesLike>[],
      constants_: PromiseOrValue<BigNumberish>[],
      stackMaxTop_: PromiseOrValue<BigNumberish>,
      stackTop_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
